### ISSUE TITLE
On the speed of  .rec  compared with .JPEG.

### ISSUE THREAD

**Issue by huangh12** [JaminFong/dali-pytorch#1]
Hi @JaminFong , I've noticed you convert the ImageNet dataset to MXNet RecordIO format. 
Did you observe the rec format being faster than reading the raw .jpeg image in your DALI experiments?
Thanky you.

**Comment by JaminFong** [comment]
Yes, reading rec is much faster than raw .jpeg image, especially on non-ssd devices.

**Comment by huangh12** [comment]
Cool！
